### ISSUE TITLE
Getting timeout from MongoDB Atlas

### ISSUE THREAD

**Issue by felipe-casali** [mongodb/mongo-jdbc-driver#124]
I'm trying to use this string to connect into a MongoDB Atlas, but it's failing with timeout.
Is there something I missed on the string structure?

jdbc:mongodb://user:password@clustermongodb.xqslipn.mongodb.net/myFirstDatabase

I realized that the clustermongodb.xqslipn.mongodb.net is not resolving with nslookup, but I'm not sure if it's the problem because I was able to connect from the same host using the mongosh.

**Comment by jchemburkar** [comment]
Hi @felipe-casali , one thing to address your issue would be to set a timeout in the connection string. For example, to your above url, you could append `?connectTimeoutMS=<milliseconds>`. Similarly, socket timeout can be set as well. More information on what options can be set in the connection string can be found [here](https://www.mongodb.com/docs/manual/reference/connection-string/)!
