### ISSUE TITLE
Error when try to connect to MongoDB

### ISSUE THREAD

**Issue by leandroidvlab** [mongodb/mongo-jdbc-driver#128]
When I try to connect in MongoDB server, I get this error:

`Command failed with error 59 (CommandNotFound): 'no such command: 'sqlGetResultSchema'' on server`

This is the URL connection:

`jdbc:mongodb://10.1.1.53:27017/interviewTest`

**Comment by rychipman** [comment]
Hi @leandroidvlab, the JDBC driver is currently for connecting to MongoDB Atlas SQL -- you can't use it to connect to a normal `mongod` or `mongos`. The first couple documentation links in the README will point you to some more info about what Atlas SQL is and how to use it!
