### ISSUE TITLE
jdbc getColumns only works for admin

### ISSUE THREAD

**Issue by ryanhamilton** [mongodb/mongo-jdbc-driver#137]
Hi,

I was attempting to call various forms of getColumns but was getting a permissions error.
It seems a user needs to be admin to get the list of tables, this seems unusual.
I think usually at least the tables a user is permissioned to see are shown.

```
r = getColumns(serverConfig, null, null, "%", "%");
r = getColumns(serverConfig, null, null, null, null);
```

This is using Atlas today (2023-08-01) with JDBC driver mongodb-jdbc-2.0.2-all.jar.

Once I assign myself admin permissions, the tables are returned.

**Comment by jchemburkar** [comment]
@ryanhamilton you have the correct understanding, but to clarify, the user needs the following for the tables to be returned:

Custom Roles:
- SqlGetSchema on the database
- find on the database
- SqlSetSchema on the database (unless using the SQL quickstart flow)

Privileges:
- read on the database
