### ISSUE TITLE
commons-lang3 3.0 clashes with later commons-lang3 versions

### ISSUE THREAD

**Issue by jrbocarsly** [mongodb/mongo-jdbc-driver#297]
Hi
The MongoDB Atlas driver (mongodb-jdbc-2.2.0-all.jar) which has a dependency of commons-lang3-3.0.0.jar, may clash when called from projects using higher lang3 versions (we are using 3.17.0). Could you upgrade, or announce when the driver will be upgraded?
Many thanks
J Bocarsly

**Comment by terakilobyte** [comment]
@jrbocarsly Thanks for the issue. I've got a #307 which upgrades this on our latest development branch. We except this to be folded back into the main branch sometime early in the new year. Do you need it before then?

**Comment by jrbocarsly** [comment]
Thanks for your response. The timeframe sounds fine for our needs. Much appreciated.
