### ISSUE TITLE
Query schema information

### ISSUE THREAD

**Issue by ChrisLahaye** [mongodb/mongo-jdbc-driver#312]
Hello,

Is it currently possible to query schema information using SQL? For example to get a list of tables.

The query `SELECT * FROM information_schema.tables` results in the error `Error 1016: unknown collection 'tables' in database 'information_schema', correlationID = 1810409ef45ca3839ca7bc02`.

Thank you

**Comment by mattChiaravalloti** [comment]
Hey @ChrisLahaye,

Atlas SQL does not support the `information_schema` database -- there is no way to query schema information using SQL queries at this time. Atlas SQL schemas are managed in Atlas Data Federation. You could view and manage your schemas via the Atlas UI online, or by using the `sqlGetSchema`, `sqlSetSchema`, and `sqlGenerateSchema` commands in `mongosh`. You could read more about Atlas SQL schema management [here](https://www.mongodb.com/docs/atlas/data-federation/query/sql/schema-management/).

**Comment by mattChiaravalloti** [comment]
Hello again. We are going to close this issue since the question has been answered. Please feel free to re-open if you have further questions.

**Comment by ChrisLahaye** [comment]
Thank you for the response @mattChiaravalloti . The DatabaseMetaData interface works for me. Might be a good idea to support the information schema database in the future as many SQL tools depend on it.
