### ISSUE TITLE
Passing database via connection string doesn't work

### ISSUE THREAD

**Issue by OiNutter** [mongodb/mongo-jdbc-driver#33]
With JDBC you should be able to specify the database via the connection string, not by having to pass it in the info argument. At the moment this will cause a NullPointerException as it fails the Preconditions check in MongoStatement.

**Comment by rychipman** [comment]
@OiNutter could you provide an example of a connection string with database that you expect the JDBC driver to be able to handle?

**Comment by mmpataki** [comment]
@rychipman I have submitted a PR, can you please review it

**Comment by RaoulHofmann** [comment]
Is there a workaround for this? I need to use the driver with DataSourceProperties but can't pass in the database

**Comment by osowskit** [comment]
+1 to this request. Ideally the `database` parameter can be passed in the URL parameters

**Comment by jchemburkar** [comment]
This feature is now supported, as of [this](https://github.com/mongodb/mongo-jdbc-driver/commit/655fdf34c83ad00348bfdd7866599c9cdb0cf35e) commit. Similar to mongodb uris, this will come after the host / port. For example `jdbc:mongodb://<host>:<port>/<database>?authSource=<auth db>`. Please note that if the database is specified in the connection string and in the info, the latter will take precedence.
