### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by GeorgeV220** [mongodb/mongo-jdbc-driver#38]
Hello,
i'm trying to do SQL queries but i get this error:
`com.mongodb.MongoCommandException: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$sql'' on server 127.0.0.1:27017. The full response is {"ok": 0.0, "errmsg": "Unrecognized pipeline stage name: '$sql'", "code": 40324, "codeName": "Location40324"}`

**Comment by rychipman** [comment]
Hi @GeorgeV220, it sounds like you're trying to use this JDBC driver with MongoDB Server. This driver is currently only designed for use with [Atlas Data Lake](https://www.mongodb.com/atlas/data-lake)

**Comment by GeorgeV220** [comment]
Hey,
thank you for your answer.
You have any plans to support MongoDB server ?

**Comment by rychipman** [comment]
No, not at this time

**Comment by GeorgeV220** [comment]
Okay thank you very much!!
